
import React, { createContext, useContext, useState, ReactNode } from 'react';

// English Translations
const en = {
  sidebar: {
    dashboard: "Dashboard",
    charts: "Charts",
    journal: "Journal",
    playbook: "Playbook",
    reports: "Reports",
    plans: "Notebook",
    psychology: "Psychology",
    calendar: "Calendar",
    aiCoach: "AI Coach",
    plaza: "Social Plaza",
    academy: "Academy",
    notifications: "Notifications",
    tierPro: "PRO",
    tierElite: "ELITE",
    tierFree: "BASIC",
    upgrade: "Upgrade to Pro",
    guide: "Guide Mode",
    lightMode: "Light Mode",
    darkMode: "Dark Mode"
  },
  playbook: {
      title: "Playbook",
      create: "Create New Playbook",
      netPnl: "Net P&L",
      winRate: "Win Rate",
      profitFactor: "Profit Factor",
      expectancy: "Expectancy",
      avgWinner: "Average Winner",
      avgLoser: "Average Loser",
      missedTrades: "Missed Trades",
      reviewBtn: "Review your Playbook's performance",
      detail: {
          back: "Back to Playbook",
          tabs: {
              overview: "Overview",
              rules: "Playbook Rules",
              executed: "Executed Trades",
              missed: "Missed Trades",
              notes: "Notes"
          },
          table: {
              openDate: "Open Date",
              symbol: "Symbol",
              status: "Status",
              closeDate: "Close Date",
              entryPrice: "Entry Price",
              exitPrice: "Exit Price",
              netPnl: "Net P&L",
              netRoi: "Net ROI",
              setups: "Setups",
              account: "Account Name"
          }
      }
  },
  login: {
    title: "Welcome Back",
    subtitle: "Scan to login or use your credentials",
    scanTip: "Scan with Mobile App",
    scanned: "QR Code Scanned!",
    secure: "Secure Connection",
    mobile: "Mobile Compatible"
  },
  dashboard: {
    marketHours: {
      open: "OPEN",
      closed: "CLOSED",
      configure: "Configure",
      sydney: "Sydney",
      asia: "Tokyo",
      hongKong: "Hong Kong",
      frankfurt: "Frankfurt",
      london: "London",
      newYork: "New York",
      limitError: "Select up to 4 markets"
    },
    greeting: {
        morning: "Good morning, Trader!",
        noon: "Good afternoon, Trader!",
        afternoon: "Good afternoon, Trader!",
        evening: "Good evening, Trader!"
    },
    rank: {
      title: "Trader Rank",
      progress: "Progress to next rank",
      viewLeaderboard: "View Global Leaderboard",
      tiers: {
        bronze: "Bronze",
        silver: "Silver",
        gold: "Gold",
        platinum: "Platinum",
        blackGold: "Black Gold",
        legend: "Legend"
      }
    },
    riskAlert: "Risk Limit Reached",
    riskAlertDesc: "You have lost ${current} today. Limit is ${limit}.",
    riskStatus: {
      ok: "Risk Status: OK",
      okDesc: "You are trading within limits.",
      dailyPnl: "Daily PnL",
      limit: "Limit"
    },
    netPnl: "Net P&L",
    winRate: "Win Rate",
    profitFactor: "Profit Factor",
    todayPnl: "Today's P&L",
    equityCurve: "Equity Curve",
    setupPerformance: "Strategy Performance",
    aiTips: {
      title: "AI Insights",
      loading: "Analyzing your recent trades...",
      fallback: "No insights available yet. Log more trades!",
      avoid: "Avoid mistake",
      good: "Good execution recently.",
      focus: "Focus on setup",
      note: "Note"
    },
    goals: {
        title: "Weekly Goal",
        subtitle: "Keep pushing!",
        current: "Current",
        target: "Target",
        achieved: "GOAL HIT!",
        history: "View History",
        type: "Metric",
        modalTitle: "Set Weekly Goal",
        types: {
            amount: "Profit Amount ($)",
            percentage: "Percentage Gain (%)",
            r_multiple: "R-Multiples (R)"
        }
    },
    todo: {
        title: "Action Items",
        daily: "Daily Review",
        weekly: "Weekly Review",
        monthly: "Monthly Review",
        unreviewed: "Unreviewed Trades",
        completed: "Completed",
        pending: "Pending",
        start: "Start",
        system: "System",
        manual: "Manual"
    },
    tracker: {
        save: "Save Goal"
    },
    discipline: {
        streak: "Discipline Streak",
        rituals: "Daily Rituals (+10XP)",
        success: "Success",
        fail: "Fail",
        empty: "Empty",
        addRule: "Add new rule...",
        done: "Done",
        active: "Active"
    },
    level: {
        current: "Current Level",
        lifetimeXp: "Total Lifetime XP:"
    },
    equityChart: {
        current: "Current:",
        initial: "Initial:"
    }
  },
  leaderboard: {
      title: "Futures Leaderboard",
      subtitle: "Rise to the Top 200 & Claim Your Share",
      prizePool: "Prize Pool",
      registeredUsers: "No. of Registered Users",
      unlockedPool: "Unlocked Prize Pool ($)",
      dailyRank: "Daily Ranking",
      weeklyRank: "Weekly Ranking",
      monthlyRank: "Monthly Ranking",
      pnlRanking: "PNL Amount Ranking",
      volRanking: "Trading Volume Ranking",
      desc: "Top 200 by PNL share double rewards based on their PNL and trading volume rankings.",
      countdown: "Monthly Leaderboard closes in",
      register: "Register Now",
      invite: "Invite & Earn",
      table: {
          rank: "Ranking",
          user: "UID/User Nickname",
          pnl: "PNL Amount ($)",
          reward: "Reward ($)",
          interactions: "Interactions"
      },
      recommend: "Follow"
  },
  social: {
      title: "Social Leaderboard",
      friends: "Friends",
      addModalTitle: "Add Friend",
      namePlaceholder: "Friend's Name",
      simulated: "This adds a simulated friend for demo purposes.",
      addBtn: "Add Friend",
      search: "Search friends...",
      online: "Online",
      offline: "Offline",
      noMessages: "No messages yet.",
      typeMessage: "Type a message..."
  },
  calendar: {
      title: "Trading Calendar",
      totalPnl: "Total P&L",
      totalTrades: "Total Trades",
      weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
      modal: {
          stats: "Day Stats",
          wins: "Wins",
          avgWin: "Avg Win",
          avgLoss: "Avg Loss",
          trades: "Trades",
          dailyReview: "Daily Review",
          writeReview: "Write your daily review here...",
          save: "Save Review",
          saveSuccess: "Review saved!"
      }
  },
  journal: {
      title: "Trade Journal",
      addTrade: "Add Trade",
      searchPlaceholder: "Search symbol, setup...",
      date: "Date",
      symbol: "Symbol",
      direction: "Direction",
      setup: "Setup",
      screenshot: "Screenshot",
      pnl: "P&L",
      actions: "Actions",
      long: "LONG",
      short: "SHORT",
      reviewed: "Reviewed",
      pendingReview: "Pending Review",
      uploadFailed: "Image upload failed.",
      saveSuccess: "Trade saved successfully.",
      stopTradingTitle: "STOP TRADING",
      consecutiveLossDesc: "You have hit {count} consecutive losses.",
      dailyLossDesc: "You have hit your daily loss limit of ${limit}.",
      consecutiveLossAction: "Take a break. Reset.",
      consecutiveLossReset: "Resets in",
      consecutiveLossAck: "I Acknowledge",
      preTrade: {
          title: "Pre-Trade Checklist",
          subtitle: "Clear your mind before entering.",
          addItem: "Add item...",
          moodTitle: "Current Mood",
          moodWarning: "Trading while emotional is risky.",
          progress: "Progress",
          proceed: "Proceed to Log Trade",
          proceedRisky: "Still Trade (High Risk)",
          moods: {
              calm: "Calm",
              excited: "Excited",
              anxious: "Anxious",
              angry: "Angry",
              bored: "Bored"
          }
      },
      modalTitle: "Log Trade",
      modalSubtitle: "Log a new trade execution",
      detailsTab: "Details",
      reviewTab: "Review & Mistake",
      entryDate: "Entry Date",
      exitDate: "Exit Date",
      entryPrice: "Entry Price",
      exitPrice: "Exit Price",
      quantity: "Quantity",
      fees: "Fees",
      notes: "Notes",
      reviewNotes: "Review Notes",
      mistakes: "Mistakes",
      mistakesPlaceholder: "Add tag (e.g. FOMO)...",
      uploadImage: "Upload Image",
      openTradeHint: "Exit date missing. Trade will be marked as OPEN.",
      cancel: "Cancel",
      save: "Save Trade",
      showDuration: "Show Duration",
      duration: "Duration",
      daily: {
          netPnl: "Net P&L",
          viewNote: "View Note",
          intradayCurve: "Intraday Equity Curve",
          totalTrades: "Total Trades",
          winners: "Winners",
          winRate: "Winrate",
          losers: "Losers",
          grossPnl: "Gross P&L",
          commissions: "Commissions",
          volume: "Volume",
          profitFactor: "Profit Factor",
          closeDetails: "Close Details"
      },
      // Form Specific Labels (New)
      asset: "ASSET",
      directionLabel: "DIRECTION",
      openTimeLabel: "OPEN TIME",
      closeTimeLabel: "CLOSE TIME",
      executionData: "EXECUTION DATA",
      riskManagement: "RISK MANAGEMENT",
      entryLabel: "Entry",
      exitLabel: "Exit",
      sizeLabel: "Size",
      leverageLabel: "Lev.",
      riskAmountLabel: "Risk Amount",
      netPnlLabel: "NET P&L",
      selectStrategy: "Select Strategy...",
      openPositionStatus: "Open Position"
  },
  reports: {
    title: "Reports & Analytics",
    tabs: {
        overview: "OVERVIEW",
        detailed: "DETAILED",
        risk: "RISK",
        calendar: "CALENDAR",
        ai: "AI INSIGHTS",
        options: "OPTIONS",
        winsLosses: "WINS VS LOSSES",
        compare: "COMPARE"
    },
    filters: {
        label: "Filter By:",
        days: "DAYS",
        weeks: "WEEKS",
        months: "MONTHS",
        time: "TIME",
        duration: "TRADE DURATION",
        timeInterval: "Select Time Interval",
        other: "OTHER",
        price: "PRICE",
        volume: "VOLUME",
        instrument: "INSTRUMENT",
        sector: "SECTOR",
        setups: "SETUPS",
        mistakes: "MISTAKES",
        tags: "TAGS"
    },
    stats: {
        bestMonth: "Best Month",
        lowestMonth: "Lowest Month",
        avgMonth: "Average (Per Month)",
        peakPerformance: "Peak Performance",
        maxDrawdown: "Maximum Drawdown Period",
        consistentBaseline: "Consistent Baseline",
        yourStats: "YOUR STATS (ALL DATES)",
        totalPnl: "Total P&L",
        avgDailyVol: "Average Daily Volume",
        avgWin: "Average Winning Trade",
        avgLoss: "Average Losing Trade",
        totalTrades: "Total Number of Trades",
        winCount: "Number of Winning Trades",
        lossCount: "Number of Losing Trades",
        beCount: "Number of Break Even Trades",
        maxConWins: "Max Consecutive Wins",
        maxConLoss: "Max Consecutive Losses",
        commissions: "Total Commissions & Fees",
        totalSwap: "Total Swap",
        largestProfit: "Largest Profit",
        largestLoss: "Largest Loss",
        avgHoldAll: "Average Hold Time (All Trades)",
        avgHoldWin: "Average Hold Time (Winning Trades)",
        avgHoldLoss: "Average Hold Time (Losing Trades)",
        avgHoldScratch: "Average Hold Time (Scratch Trades)",
        avgTradePnl: "Average Trade P&L",
        profitFactor: "Profit Factor",
        openTrades: "Open Trades",
        totalDays: "Total Trading Days",
        winningDays: "Winning Days",
        losingDays: "Losing Days",
        beDays: "Breakeven Days",
        loggedDays: "Logged Days",
        maxConWinDays: "Max Consecutive Winning Days",
        maxConLossDays: "Max Consecutive Losing Days",
        avgDailyPnl: "Average Daily P&L",
        largestLosingDay: "Largest Losing Day (Losses)",
        avgPlannedR: "Average Planned R-Multiple",
        avgRealizedR: "Average Realized R-Multiple",
        expectancy: "Trade Expectancy"
    },
    charts: {
        equityTitle: "Daily Net Cumulative P&L",
        dailyPnlTitle: "Daily Net P&L",
        distTitle: "Trade Distribution by",
        perfTitle: "Performance by",
        allDates: "(All Dates)"
    },
    table: {
        summary: "Summary",
        netProfits: "Net Profits",
        winPct: "Winning %",
        totalProfits: "Total Profits",
        totalLoss: "Total Loss",
        trades: "Trades"
    },
    calendar: {
        totalPnl: "Total P&L",
        winRate: "Win Rate",
        activeDays: "Active Days",
        weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"]
    }
  },
  plans: {
      dailyJournal: "Daily Journal",
      weeklyReview: "Weekly Review",
      monthlyReview: "Monthly Review",
      chartAnalysis: "Chart Analysis",
      templates: "Templates",
      strategies: "Strategies",
      allNotes: "All Notes",
      addFolder: "New Folder",
      folders: "FOLDERS",
      tags: "TAGS",
      recentlyDeleted: "Trash",
      selectAll: "Select All",
      addNote: "New Note",
      noNotes: "No notes found.",
      untitled: "Untitled Note",
      created: "Created",
      lastUpdated: "Updated",
      delete: "Delete",
      linkTradesBtn: "Link Trades",
      addTag: "Add Tag",
      saveAsTemplate: "Save as Template",
      selectTemplate: "Select Template",
      insertTemplate: "Insert Template",
      useTemplate: "Use",
      selectTrades: "Select Trades to Link",
      selectNote: "Select Note",
      selectNotePlaceholder: "Select a note to view",
      selectNoteDesc: "Choose a note from the list or create a new one.",
      confirmDelete: "Delete folder \"{folder}\"? Notes will be kept in All Notes.",
      managePrompt: "Manage \"{folder}\": Type 'rename' or 'delete'",
      editor: {
        normal: "Normal",
        h1: "Title (H1)",
        h2: "Subtitle (H2)",
        code: "Code Block",
        undo: "Undo",
        redo: "Redo",
        bold: "Bold",
        italic: "Italic",
        underline: "Underline",
        strike: "Strikethrough",
        left: "Align Left",
        center: "Align Center",
        right: "Align Right",
        bullet: "Bullet List",
        number: "Numbered List",
        link: "Insert Link",
        image: "Insert Image",
        clear: "Clear Formatting",
        fontName: "Font",
        fontSize: "Size"
      },
      strategyLib: {
          title: "Strategy Library",
          technicals: "Technical Checklist",
          addStrategy: "Add Strategy",
          delete: "Delete Strategy",
          addItem: "Add checklist item...",
          progress: "Progress"
      },
      summary: {
          trades: "Trades",
          volume: "Volume",
          commissions: "Commissions",
          grossPnl: "Gross P&L"
      }
  },
  risk: {
        settingsTitle: "Risk Settings",
        accountSize: "Account Size",
        maxDailyLoss: "Max Daily Loss",
        maxTradeRisk: "Max Trade Risk",
        maxConsecutiveLosses: "Max Consecutive Losses",
        saveSettings: "Save Settings",
        saveSuccess: "Settings saved successfully",
        reviewTitle: "Review Routine",
        dailyReview: "Daily Review",
        dailyDesc: "End of day",
        weeklyReview: "Weekly Review",
        weeklyDesc: "End of week",
        monthlyReview: "Monthly Review",
        monthlyDesc: "End of month",
        completed: "Done",
        checkIn: "Check In",
        rulesTitle: "Trading Rules",
        rulesDesc: "Non-negotiables",
        noRules: "No rules defined.",
        addRulePlaceholder: "New rule...",
        add: "Add",
        tooltips: {
            accountSize: "Your total trading capital. This is the base for percentage calculations.",
            maxDailyLoss: "Hard stop limit. If you lose this amount in a single day, you MUST stop trading.",
            maxTradeRisk: "The maximum amount you are willing to lose on a SINGLE trade (Stop Loss amount).",
            maxConsecutiveLosses: "Stop trading after this many losses in a row to prevent emotional tilting.",
            maxOpenPositions: "Limit the number of simultaneous active trades to maintain focus.",
            dailyProfitTarget: "A soft goal to secure profits. Consider walking away or reducing size when hit.",
            experience: "Years of active trading participation.",
            painThreshold: "The dollar amount of loss in a day that triggers emotional instability.",
            riskAppetite: "How aggressive you are with position sizing and volatility."
        },
        simulator: {
            title: "Equity Simulator",
            desc: "Simulate potential outcomes",
            runSim: "Run Simulation",
            startBalance: "Start Balance",
            riskPerTrade: "Risk %",
            winRate: "Win Rate %",
            rrRatio: "R:R Ratio",
            numTrades: "Num Trades",
            finalEquity: "Final Equity",
            totalGain: "Total Gain",
            blownAccount: "ACCOUNT BLOWN",
            blownDesc: "Blown at trade #${trade}",
            highRiskParam: "High Risk",
            highRiskDesc: "Parameters suggest high ruin probability."
        }
  },
  psychology: {
      title: "Risk & Psychology Center",
      subtitle: "Master your mind, master the market",
      recalibrate: "Recalibrate Risk Profile",
      checkIn: "Emotion Check-In",
      howFeeling: "How are you feeling right now?",
      fear: "Fear",
      neutral: "Neutral",
      greed: "Greed",
      meditation: "Mindfulness Reset",
      meditationDesc: "Take 60 seconds to breathe before your next trade.",
      startBreathe: "Start Breathing",
      breatheIn: "Breathe In...",
      hold: "Hold...",
      breatheOut: "Breathe Out...",
      hacks: "Mental Hacks",
      hack1: "Am I trading my plan or my P&L?",
      hack2: "The market doesn't know you exist.",
      hack3: "Best loser wins."
  },
  aiCoach: {
      title: "AI Trading Coach",
      subtitle: "Your personal analyst.",
      analyzeBtn: "Analyze My Trading",
      analyzing: "Analyzing {count} trades...",
      summary: "Performance Summary",
      coachMessage: "Coach's Message",
      reAnalyze: "Re-analyze",
      error: "Analysis failed. Please try again."
  },
  plaza: {
      whatsNew: "What's on your mind?",
      post: "Post",
      feed: "Feed",
      following: "Following",
      followers: "followers",
      follow: "Follow",
      followingBtn: "Following",
      selectTrade: "Select Trade",
      selectNote: "Select Note",
      attachTrade: "Attach Trade",
      attachNote: "Attach Note",
      quoted: "Replying to",
      shareQuote: "Quote Post",
      writeComment: "Write a comment..."
  },
  academy: {
      title: "Trading Academy",
      subtitle: "Learn from the best.",
      search: "Search courses...",
      filters: {
          all: "All Courses",
          free: "Free",
          premium: "Premium"
      },
      course: {
          start: "Start Course"
      },
      exam: {
          title: "Assessment Center",
          cfaTitle: "CFA Level II & III Mock Exam",
          cfaDesc: "Test your knowledge with 50 rigorous multiple-choice questions curated from historical CFA standards.",
          startBtn: "Take Exam",
          retakeBtn: "Retake Exam",
          resultsTitle: "Your Performance Report",
          scoreLabel: "Final Score",
          ratingLabel: "Academic Rating",
          aiAnalysis: "AI Knowledge Audit",
          backToAcademy: "Back to Academy",
          evaluation: {
              expert: "Expert - Competitive for Level III Excellence",
              advanced: "Advanced - Solid Pass Candidate",
              intermediate: "Intermediate - Near Minimum Passing Score (MPS)",
              basic: "Basic - Needs significant conceptual study",
              poor: "Fail - Foundational gaps identified"
          }
      }
  },
  pricing: {
      mostPopular: "MOST POPULAR",
      upgrade: "Upgrade"
  },
  settings: {
      title: "Settings",
      menu: {
          publicProfile: "Public Profile",
          privacy: "Privacy",
          accountHeader: "ACCOUNT",
          account: "Account",
          sessions: "Sessions",
          billingHeader: "BILLING",
          subscription: "Subscription",
          payment: "Payment Methods",
          history: "Billing History",
          notificationsHeader: "NOTIFICATIONS",
          alerts: "Alerts",
          apiSync: "API Sync"
      },
      profile: {
          photoTitle: "Profile Photo",
          photoDesc: "This will be displayed on your profile.",
          uploadBtn: "Upload New",
          usernameLabel: "Username",
          changeUserBtn: "Change Username",
          socialTitle: "Social Links",
          wechat: "WeChat",
          bilibili: "Bilibili",
          douyin: "Douyin",
          weibo: "Weibo",
          website: "Website",
          saveBtn: "Save Changes"
      },
      api: {
          title: "Exchange API Sync",
          desc: "Connect your exchange to automatically import trade history. Read-only permissions required.",
          addBtn: "Connect Exchange",
          exchangeLabel: "Exchange",
          keyLabel: "API Key",
          secretLabel: "Secret Key",
          connect: "Connect & Sync",
          connected: "Connected",
          syncing: "Syncing...",
          lastSync: "Last Sync",
          remove: "Remove",
          disclaimer: "We only use read-only permissions to fetch order history. Your keys are encrypted locally."
      }
  },
  notifications: {
      title: "Notifications",
      pending: "Pending",
      processed: "Processed",
      markAllRead: "Mark all as read",
      empty: "No notifications"
  },
  calculator: {
      title: "Position Calculator",
      subtitle: "Sizing is everything",
      balance: "Account Balance",
      risk: "Risk %",
      entry: "Entry Price",
      stopLoss: "Stop Loss",
      target: "Take Profit",
      results: "Results",
      units: "Position Size (Units)",
      riskAmount: "Risk Amount ($)",
      fiveStep: "Execution Checklist",
      step1: "Trend is confirmed?",
      step2: "Key level rejected?",
      step3: "Stop loss protected?",
      step4: "Risk accepted?",
      step5: "No major news?"
  },
  // Added FAB, Tour, Landing translations to EN
  fab: {
      post: "Post",
      postHint: "Share to Plaza",
      note: "Note",
      noteHint: "Quick Note",
      chat: "Chat",
      chatHint: "Ask AI",
      trade: "Trade",
      tradeHint: "Log Trade"
  },
  tour: {
      sidebar: "Navigation Sidebar",
      sidebarDesc: "Access all modules here.",
      dashboardStats: "Key Statistics",
      dashboardStatsDesc: "Quick overview of your performance.",
      weeklyGoal: "Weekly Goal",
      weeklyGoalDesc: "Track your targets here.",
      charts: "Charts",
      chartsDesc: "Analyze charts and take notes.",
      journal: "Journal",
      journalDesc: "Log and review trades.",
      reports: "Reports",
      reportsDesc: "Deep dive analytics.",
      notebook: "Notebook",
      notebookDesc: "Plan trades and document strategies.",
      risk: "Risk & Psychology",
      riskDesc: "Manage risk and mindset.",
      calendar: "Calendar",
      calendarDesc: "View trades by date.",
      aiCoach: "AI Coach",
      aiCoachDesc: "Get automated insights.",
      plaza: "Social Plaza",
      plazaDesc: "Connect with other traders.",
      academy: "Academy",
      academyDesc: "Learn new skills."
  },
  landing: {
      heroTitle: "Master Your Edge.\nScale Your Success.",
      heroSubtitle: "The all-in-one trading journal, analytics, and mentor platform.",
      ctaStart: "Start Trading",
      ctaDemo: "View Demo",
      trustedBy: "Trusted by Traders at",
      tabs: {
          journal: "Journal",
          analytics: "Analytics",
          ai: "AI Coach",
          risk: "Risk Mgmt"
      },
      stats: {
          users: "Active Traders",
          trades: "Trades Logged",
          rating: "User Rating"
      },
      featureSections: {
          importTitle: "Seamless Import",
          importDesc: "Connect with top brokers or import via CSV in seconds.",
          importList: ["Auto-Sync", "CSV Support", "API Integration"]
      },
      footer: {
          features: "Features",
          pricing: "Pricing",
          resources: "Resources",
          product: "Product",
          company: "Company",
          changelog: "Changelog",
          download: "Download",
          blog: "Blog",
          academy: "Academy",
          help: "Help Center",
          community: "Community",
          about: "About",
          careers: "Careers",
          legal: "Legal",
          privacy: "Privacy",
          terms: "Terms"
      },
      footerRights: "All rights reserved."
  },
  gates: {
      lockedTitle: "Feature Locked",
      lockedDesc: "Upgrade to unlock this feature.",
      unlockBtn: "Unlock Now"
  },
  referral: {
      balance: "Referral Balance",
      tabs: {
          refer: "Refer",
          redeem: "Redeem",
          stats: "Stats"
      },
      heroTitle: "Invite Friends, Earn Cash",
      heroDesc: "Share your link and earn rewards.",
      copyLink: "Your Referral Link",
      socials: {
          email: "Email",
          facebook: "Facebook",
          x: "X (Twitter)"
      },
      stats: {
          earned: "Total Earned",
          free: "Free Users",
          paid: "Paid Users"
      },
      footer: "Terms apply."
  },
  goalsPage: {
      title: "Goal History",
      streak: "Current Streak",
      weeks: "Weeks",
      bestWeek: "Best Week",
      avgCompletion: "Avg Completion",
      chartTitle: "Performance vs Target",
      weekOf: "Week Of",
      target: "Target",
      actual: "Actual",
      status: "Status"
  },
  charts: {
      title: "Chart Note",
      saveToNotebook: "Save to Notebook",
      notePlaceholder: "Start typing your analysis...",
      analyzing: "AI is analyzing chart..."
  },
  reviewSession: {
      netPnl: "Net P&L",
      winRate: "Win Rate",
      tradesInPeriod: "Trades in Period",
      noTrades: "No trades found.",
      clickForDetails: "Click a trade to view details",
      writeSummary: "Write your review summary here...",
      finish: "Finish Review"
  }
};

// Chinese Translations
const cn = {
  ...en,
  sidebar: {
    ...en.sidebar,
    dashboard: "仪表盘",
    charts: "图表分析",
    journal: "交易日志",
    playbook: "策略手册",
    reports: "报表统计",
    plans: "笔记本",
    psychology: "心态风控",
    calendar: "日历视图",
    aiCoach: "AI 教练",
    plaza: "交易广场",
    academy: "学院",
    notifications: "通知",
    tierPro: "专业版",
    tierElite: "尊享版",
    tierFree: "基础版",
    upgrade: "升级专业版",
    guide: "新手引导",
    lightMode: "浅色模式",
    darkMode: "深色模式"
  },
  playbook: {
      ...en.playbook,
      title: "策略手册",
      create: "创建新策略",
      netPnl: "净盈亏",
      winRate: "胜率",
      profitFactor: "盈亏比",
      expectancy: "期望值",
      avgWinner: "平均盈利",
      avgLoser: "平均亏损",
      missedTrades: "踏空交易",
      reviewBtn: "复盘策略表现",
      detail: {
          back: "返回策略手册",
          tabs: {
              overview: "总览",
              rules: "策略规则",
              executed: "执行交易",
              missed: "踏空交易",
              notes: "笔记"
          },
          table: {
              openDate: "开仓时间",
              symbol: "品种",
              status: "状态",
              closeDate: "平仓时间",
              entryPrice: "入场价",
              exitPrice: "出场价",
              netPnl: "净利润",
              netRoi: "回报率",
              setups: "设置",
              account: "账户名称"
          }
      }
  },
  login: {
    title: "欢迎回来",
    subtitle: "扫描二维码或使用账号登录",
    scanTip: "使用手机App扫描",
    scanned: "扫描成功！",
    secure: "安全连接",
    mobile: "移动端兼容"
  },
  dashboard: {
      ...en.dashboard,
      marketHours: {
          ...en.dashboard.marketHours,
          open: "开盘",
          closed: "休市",
          configure: "配置",
          sydney: "悉尼",
          asia: "东京",
          hongKong: "香港",
          frankfurt: "法兰克福",
          london: "伦敦",
          newYork: "纽约"
      },
      greeting: {
        morning: "早上好，交易员！",
        noon: "中午好，交易员！",
        afternoon: "下午好，交易员！",
        evening: "晚上好，交易员！"
      },
      riskAlert: "触及风控红线",
      riskAlertDesc: "今日已亏损 ${current}。限制为 ${limit}。",
      riskStatus: {
          ...en.dashboard.riskStatus,
          ok: "风控状态：安全",
          okDesc: "您在允许的亏损范围内。",
          dailyPnl: "今日盈亏",
          limit: "限制"
      },
      netPnl: "净盈亏",
      winRate: "胜率",
      profitFactor: "盈亏比",
      todayPnl: "今日盈亏",
      equityCurve: "资金曲线",
      setupPerformance: "策略表现",
      aiTips: {
          ...en.dashboard.aiTips,
          title: "AI 洞察",
          loading: "正在分析您的交易...",
          fallback: "暂无洞察，请记录更多交易！",
          avoid: "避免错误",
          good: "近期执行良好。",
          focus: "关注策略",
          note: "笔记"
      },
      rank: {
        title: "交易段位",
        progress: "距离下一段位",
        viewLeaderboard: "查看全球排行榜",
        tiers: {
          bronze: "青铜",
          silver: "白银",
          gold: "黄金",
          platinum: "铂金",
          blackGold: "黑金",
          legend: "传奇"
        }
      },
      goals: {
          ...en.dashboard.goals,
          title: "本周目标",
          subtitle: "继续保持！",
          current: "当前",
          target: "目标",
          achieved: "达成目标！",
          history: "查看历史",
          modalTitle: "设定本周目标",
          types: {
              amount: "盈利金额 ($)",
              percentage: "百分比收益 (%)",
              r_multiple: "R 倍数 (R)"
          }
      },
      todo: {
          ...en.dashboard.todo,
          title: "待办事项",
          daily: "每日复盘",
          weekly: "周度复盘",
          monthly: "月度复盘",
          unreviewed: "未复盘交易",
          completed: "已完成",
          pending: "待处理",
          start: "开始",
          system: "系统",
          manual: "手动"
      },
      tracker: {
          save: "保存目标"
      },
      discipline: {
          streak: "纪律打卡",
          rituals: "每日仪式 (+10XP)",
          success: "成功",
          fail: "失败",
          empty: "空",
          addRule: "添加新规则...",
          done: "完成",
          active: "启用"
      },
      level: {
          current: "当前等级",
          lifetimeXp: "累计总经验值："
      },
      equityChart: {
          current: "当前：",
          initial: "初始："
      }
  },
  leaderboard: {
      title: "合约争霸赛",
      subtitle: "冲击前200名 & 瓜分奖池",
      prizePool: "奖池总额",
      registeredUsers: "已报名人数",
      unlockedPool: "已解锁奖池 ($)",
      dailyRank: "日榜",
      weeklyRank: "周榜",
      monthlyRank: "月榜",
      pnlRanking: "收益额排名",
      volRanking: "交易量排名",
      desc: "收益额排名前 200 的用户将根据其收益额和交易量排名瓜分双倍奖励。",
      countdown: "月榜倒计时",
      register: "立即报名",
      invite: "邀请赚佣",
      table: {
          rank: "排名",
          user: "UID/用户昵称",
          pnl: "收益额 ($)",
          reward: "预计奖励 ($)",
          interactions: "互动"
      },
      recommend: "关注"
  },
  social: {
      ...en.social,
      friends: "好友",
      title: "社交排行榜",
      addModalTitle: "添加好友",
      namePlaceholder: "好友名称",
      simulated: "此功能添加模拟好友。",
      addBtn: "添加好友",
      search: "搜索好友...",
      online: "在线",
      offline: "离线",
      noMessages: "暂无消息。",
      typeMessage: "输入消息..."
  },
  journal: {
      ...en.journal,
      title: "交易日志",
      addTrade: "添加交易",
      searchPlaceholder: "搜索代码、策略...",
      date: "日期",
      symbol: "代码",
      direction: "方向",
      setup: "策略",
      screenshot: "截图",
      pnl: "盈亏",
      actions: "操作",
      long: "做多",
      short: "做空",
      reviewed: "已复盘",
      pendingReview: "待复盘",
      uploadFailed: "图片上传失败。",
      saveSuccess: "交易保存成功。",
      stopTradingTitle: "停止交易",
      consecutiveLossDesc: "您已连续亏损 {count} 笔。",
      dailyLossDesc: "您已达到单日亏损上限 ${limit}。",
      consecutiveLossAction: "休息一下。重置状态。",
      consecutiveLossReset: "重置倒计时",
      consecutiveLossAck: "我已知晓",
      preTrade: {
          ...en.journal.preTrade,
          title: "交易前检查清单",
          subtitle: "入场前保持清醒。",
          addItem: "添加项目...",
          moodTitle: "当前情绪",
          moodWarning: "情绪化交易风险极高。",
          progress: "进度",
          proceed: "继续记录",
          proceedRisky: "仍然继续 (高风险)",
          moods: {
              calm: "平静",
              excited: "兴奋",
              anxious: "焦虑",
              angry: "愤怒",
              bored: "无聊"
          }
      },
      modalTitle: "记录交易",
      modalSubtitle: "记录新的交易数据",
      detailsTab: "详情",
      reviewTab: "复盘与错误",
      entryDate: "开仓时间",
      exitDate: "平仓时间",
      entryPrice: "开仓价",
      exitPrice: "平仓价",
      quantity: "数量",
      fees: "手续费",
      notes: "笔记",
      reviewNotes: "复盘笔记",
      mistakes: "错误标签",
      mistakesPlaceholder: "添加标签 (如：踏空)...",
      uploadImage: "上传图片",
      openTradeHint: "缺少平仓时间，将标记为持仓中。",
      cancel: "取消",
      save: "保存交易",
      showDuration: "显示持仓时长",
      duration: "持仓时长",
      daily: {
          netPnl: "净盈亏",
          viewNote: "查看笔记",
          intradayCurve: "日内资金曲线",
          totalTrades: "总交易数",
          winners: "盈利笔数",
          winRate: "胜率",
          losers: "亏损笔数",
          grossPnl: "毛盈亏",
          commissions: "手续费",
          volume: "交易量",
          profitFactor: "盈亏比",
          closeDetails: "关闭详情"
      },
      // Form Specific Labels (New)
      asset: "交易标的",
      directionLabel: "交易方向",
      openTimeLabel: "开仓时间",
      closeTimeLabel: "平仓时间",
      executionData: "执行数据",
      riskManagement: "风险管理",
      entryLabel: "开仓价格",
      exitLabel: "平仓价格",
      sizeLabel: "仓位数量",
      leverageLabel: "杠杆倍数",
      riskAmountLabel: "风险金额 ($)",
      netPnlLabel: "净盈亏",
      selectStrategy: "选择策略...",
      openPositionStatus: "持仓中 (未平仓)"
  },
  reports: {
    title: "报表统计",
    tabs: {
        overview: "概览",
        detailed: "详细报表",
        risk: "风控分析",
        calendar: "交易日历",
        ai: "AI 智能周报",
        options: "期权分析",
        winsLosses: "盈亏对比",
        compare: "周期对比"
    },
    filters: {
        label: "筛选维度:",
        days: "按天",
        weeks: "按周",
        months: "按月",
        time: "按时段",
        duration: "持仓时间",
        timeInterval: "选择时间间隔",
        other: "其他",
        price: "价格",
        volume: "交易量",
        instrument: "品种",
        sector: "板块",
        setups: "策略",
        mistakes: "错误",
        tags: "标签"
    },
    stats: {
        bestMonth: "最佳月份",
        lowestMonth: "最差月份",
        avgMonth: "月均盈亏",
        peakPerformance: "历史最佳表现",
        maxDrawdown: "最大回撤周期",
        consistentBaseline: "平均基准水平",
        yourStats: "统计数据 (所有日期)",
        totalPnl: "总盈亏",
        avgDailyVol: "日均交易量",
        avgWin: "平均盈利",
        avgLoss: "平均亏损",
        totalTrades: "总交易笔数",
        winCount: "盈利笔数",
        lossCount: "亏损笔数",
        beCount: "持平笔数",
        maxConWins: "最大连胜",
        maxConLoss: "最大连败",
        commissions: "手续费总额",
        totalSwap: "隔夜费",
        largestProfit: "最大单笔盈利",
        largestLoss: "最大单笔亏损",
        avgHoldAll: "平均持仓时间 (全部)",
        avgHoldWin: "平均持仓时间 (盈利)",
        avgHoldLoss: "平均持仓时间 (亏损)",
        avgHoldScratch: "平均持仓时间 (持平)",
        avgTradePnl: "每笔平均盈亏",
        profitFactor: "盈亏比 (PF)",
        openTrades: "持仓中",
        totalDays: "总交易天数",
        winningDays: "盈利天数",
        losingDays: "亏损天数",
        beDays: "持平天数",
        loggedDays: "记录天数",
        maxConWinDays: "最长连红天数",
        maxConLossDays: "最长连黑天数",
        avgDailyPnl: "日均盈亏",
        largestLosingDay: "最大单日亏损",
        avgPlannedR: "平均计划 R盈亏比",
        avgRealizedR: "平均实际 R盈亏比",
        expectancy: "交易期望值"
    },
    charts: {
        equityTitle: "每日累计净盈亏 (资金曲线)",
        dailyPnlTitle: "每日净盈亏",
        distTitle: "交易分布 -",
        perfTitle: "盈亏表现 -",
        allDates: "(所有日期)"
    },
    table: {
        summary: "数据汇总",
        netProfits: "净利润",
        winPct: "胜率",
        totalProfits: "总盈利",
        totalLoss: "总亏损",
        trades: "交易数"
    },
    calendar: {
        totalPnl: "总盈亏",
        winRate: "胜率",
        activeDays: "活跃交易日",
        weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"]
    }
  },
  risk: {
      ...en.risk,
      settingsTitle: "风控设置",
      accountSize: "账户资金",
      maxDailyLoss: "单日最大亏损",
      maxTradeRisk: "单笔最大风险",
      maxConsecutiveLosses: "最大连败次数",
      saveSettings: "保存设置",
      saveSuccess: "设置已保存",
      reviewTitle: "复盘流程",
      dailyReview: "每日复盘",
      dailyDesc: "日终总结",
      weeklyReview: "周度复盘",
      weeklyDesc: "周末总结",
      monthlyReview: "月度复盘",
      monthlyDesc: "月末总结",
      completed: "已完成",
      checkIn: "打卡",
      rulesTitle: "交易铁律",
      rulesDesc: "不可违背的原则",
      noRules: "暂无规则。",
      addRulePlaceholder: "新规则...",
      add: "添加",
      simulator: {
          ...en.risk.simulator,
          title: "资金曲线模拟",
          desc: "模拟潜在结果",
          runSim: "运行模拟",
          startBalance: "起始资金",
          riskPerTrade: "风险 %",
          winRate: "胜率 %",
          rrRatio: "盈亏比",
          numTrades: "交易次数",
          finalEquity: "最终权益",
          totalGain: "总收益",
          blownAccount: "账户爆仓",
          blownDesc: "在第 #{trade} 笔交易爆仓",
          highRiskParam: "高风险参数",
          highRiskDesc: "参数显示破产概率极高。"
      }
  },
  psychology: {
      ...en.psychology,
      title: "心态与风控中心",
      subtitle: "掌控心态，掌控市场",
      recalibrate: "重新评估风控偏好",
      checkIn: "情绪打卡",
      howFeeling: "你现在感觉如何？",
      fear: "恐惧",
      neutral: "平静",
      greed: "贪婪",
      meditation: "正念重置",
      meditationDesc: "交易前深呼吸 60 秒。",
      startBreathe: "开始呼吸",
      breatheIn: "吸气...",
      hold: "屏气...",
      breatheOut: "呼气...",
      hacks: "心态法则",
      hack1: "我在交易计划还是盈亏？",
      hack2: "市场不知道你的存在。",
      hack3: "善输者赢。"
  },
  aiCoach: {
      ...en.aiCoach,
      title: "AI 交易教练",
      subtitle: "您的私人分析师。",
      analyzeBtn: "分析我的交易",
      analyzing: "正在分析 {count} 笔交易...",
      summary: "表现总结",
      coachMessage: "教练寄语",
      reAnalyze: "重新分析",
      error: "分析失败，请重试。"
  },
  plaza: {
      ...en.plaza,
      whatsNew: "有什么想法？",
      post: "发布",
      feed: "动态",
      following: "关注",
      followers: "粉丝",
      follow: "关注",
      followingBtn: "已关注",
      selectTrade: "选择交易",
      selectNote: "选择笔记",
      attachTrade: "附带交易",
      attachNote: "附带笔记",
      quoted: "回复",
      shareQuote: "引用发布",
      writeComment: "写评论..."
  },
  academy: {
      ...en.academy,
      title: "交易学院",
      subtitle: "向最优秀的学习。",
      search: "搜索课程...",
      filters: {
          all: "全部课程",
          free: "免费",
          premium: "付费"
      },
      course: {
          start: "开始学习"
      },
      exam: {
          title: "测评中心",
          cfaTitle: "CFA 二级 & 三级 模拟考试",
          cfaDesc: "通过 50 道严格按照历年 CFA 标准编写的选择题，测试您的专业金融知识储备。",
          startBtn: "开始考试",
          retakeBtn: "重新挑战",
          resultsTitle: "测评表现报告",
          scoreLabel: "最终得分",
          ratingLabel: "学术评级",
          aiAnalysis: "AI 知识库审计",
          backToAcademy: "返回学院",
          evaluation: {
              expert: "专家级 - 具备冲击 CFA 三级优秀的实力",
              advanced: "高级 - 极具通过潜力的候选人",
              intermediate: "中级 - 接近最低通过分数线 (MPS)",
              basic: "基础 - 需加强核心概念学习",
              poor: "需努力 - 存在明显知识断层"
          }
      }
  },
  pricing: {
      ...en.pricing,
      mostPopular: "最受欢迎",
      upgrade: "升级"
  },
  notifications: {
      ...en.notifications,
      title: "通知中心",
      pending: "待处理",
      processed: "已处理",
      markAllRead: "全部已读",
      empty: "暂无通知"
  },
  calculator: {
      ...en.calculator,
      title: "仓位计算器",
      subtitle: "仓位管理是关键",
      balance: "账户余额",
      risk: "风险 %",
      entry: "入场价",
      stopLoss: "止损价",
      target: "止盈价",
      results: "计算结果",
      units: "仓位数量 (Units)",
      riskAmount: "风险金额 ($)",
      fiveStep: "执行检查清单",
      step1: "趋势确认？",
      step2: "关键位拒绝？",
      step3: "止损保护？",
      step4: "风险可接受？",
      step5: "无重大新闻？"
  },
  plans: {
      ...en.plans,
      dailyJournal: "每日复盘",
      weeklyReview: "周度复盘",
      monthlyReview: "月度复盘",
      chartAnalysis: "图表分析",
      templates: "模板",
      strategies: "策略库",
      allNotes: "所有笔记",
      addFolder: "新建文件夹",
      folders: "文件夹",
      tags: "标签",
      recentlyDeleted: "最近删除",
      selectAll: "全选",
      addNote: "新建笔记",
      noNotes: "暂无笔记。",
      untitled: "无标题笔记",
      created: "创建时间",
      lastUpdated: "最后更新",
      delete: "删除",
      linkTradesBtn: "关联交易",
      addTag: "添加标签",
      saveAsTemplate: "保存为模板",
      selectTemplate: "选择模板",
      insertTemplate: "插入模板",
      useTemplate: "使用",
      selectTrades: "选择关联交易",
      selectNote: "选择笔记",
      selectNotePlaceholder: "选择左侧笔记查看",
      selectNoteDesc: "从列表中选择或创建一个新笔记。",
      confirmDelete: "删除文件夹 \"{folder}\"？笔记将保留在“所有笔记”中。",
      managePrompt: "管理 \"{folder}\"：输入 'rename' 重命名或 'delete' 删除",
      editor: {
        normal: "正文",
        h1: "标题 (H1)",
        h2: "副标题 (H2)",
        code: "代码块",
        undo: "撤销",
        redo: "重做",
        bold: "加粗",
        italic: "斜体",
        underline: "下划线",
        strike: "删除线",
        left: "左对齐",
        center: "居中",
        right: "右对齐",
        bullet: "无序列表",
        number: "有序列表",
        link: "插入链接",
        image: "插入图片",
        clear: "清除格式",
        fontName: "字体",
        fontSize: "字号"
      },
      strategyLib: {
          title: "策略库",
          technicals: "技术面检查清单",
          addStrategy: "添加策略",
          delete: "删除策略",
          addItem: "添加检查项...",
          progress: "进度"
      },
      summary: {
          trades: "交易笔数",
          volume: "交易量",
          commissions: "手续费",
          grossPnl: "毛利润"
      }
  },
  calendar: {
      ...en.calendar,
      title: "交易日历",
      weekdays: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"]
  }
};

const LanguageContext = createContext<any>(undefined);

export const LanguageProvider = ({ children }: { children?: ReactNode }) => {
  const [language, setLanguage] = useState<'en' | 'cn'>('cn'); // Set default to 'cn'

  const t = language === 'cn' ? cn : en;

  return (
    <LanguageContext.Provider value={{ t, language, setLanguage }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
